### ISSUE TITLE
Deletion of the m4a files associated with a soundbite... fails

### ISSUE THREAD

**Issue by dfsklar** [soundwiches/soundwich-ios#20]
@tc - please help

examine the code for deleteSoundbite in Soundwich.swift

The call to NSFileManager.defaultManager().removeItemAtPath(url) always fails, e.g.:

```
Unable to delete m4a file: file:///Users/sklard/Library/Developer/CoreSimulator/Devices/94451D87-3D44-4C33-A4B8-1836D95DA120/data/Containers/Data/Application/BDA9301A-41D3-4646-8A9E-F2107EEDEEFA/Documents/soundbite-1445391124.24116.m4a
```

I know not how to proceed on this...

**Comment by tc** [comment]
i think i fixed it using a URL object rather than path
https://github.com/soundwiches/soundwich-ios/commit/cde9ddf96af20aac5835e575dda4e3fcefdc5f73
