### ISSUE TITLE
Implement "Duplicate" in an all-but-UI form... then Sklar will connect it up...

### ISSUE THREAD

**Issue by dfsklar** [soundwiches/soundwich-ios#22]
Implement "Duplicate" in an all-but-UI form... then Sklar will connect it up...

**Comment by mysterycommand** [comment]
Fixed by [b5c707f27cb36037163b7786994d62a567433544](https://github.com/soundwiches/soundwich-ios/commit/b5c707f27cb36037163b7786994d62a567433544).
