### ISSUE TITLE
V1 Designs Colors/Styleguide/etc

### ISSUE THREAD

**Issue by tc** [soundwiches/soundwich-ios#8]

**Comment by mysterycommand** [comment]
This is done as of #13. The main "storyboard" files:
![Deli Case View](https://raw.githubusercontent.com/soundwiches/soundwich-ios/master/design/exports/Deli%20Case%20View.png)
![Soundwich View](https://raw.githubusercontent.com/soundwiches/soundwich-ios/master/design/exports/Soundwich%20View.png)
